#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export HIST_STAMPS="yyyy-mm-dd"
export UID

export EDITOR=nvim
export VISUAL=nvim
export BROWSER=firefox

# This line helps xdg-open figure out how to open things.
# Very important for Calibre to open PDF files and folders.
# This was used when I used i3 with no DE
# export XDG_CURRENT_DESKTOP=XFCE

